Paths:
    QuestionsCSV: "C:\repos\chapel_quizzing\resources\questions\2023-24_practice_session.csv"
    KeyVersesCSV: "path goes here"
    ResultsDirectory: "path goes here"
NumberToGenerate: 1
# Will append ## to title
Titles: "title goes here"
