Quiz:
    Questions:
        Number: 20
        # Distribution should match question types listed in question_types,
        # Besides default question. Numbers below should sum <= 1.0
        Distribution:
            QT: 0.2
            FTV: 0.2
            MA: 0.2
        # Ratio key should be <= 1.0, set to -1 if you don't wish to control for key verses
        RatioKey: 0.5
    
    Backups:
        Number: 10
        Distribution:
            QT: 0.2
            FTV: 0.2
            MA: 0.2
        RatioKey: -1
    
